package com.yougrocery.yougrocery.models;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link GroceryItem} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractGroceryItemAssert<S extends AbstractGroceryItemAssert<S, A>, A extends GroceryItem> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractGroceryItemAssert}</code> to make assertions on actual GroceryItem.
   * @param actual the GroceryItem we want to make assertions on.
   */
  protected AbstractGroceryItemAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual GroceryItem's amount is equal to the given one.
   * @param amount the given amount to compare the actual GroceryItem's amount to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GroceryItem's amount is not equal to the given one.
   */
  public S hasAmount(int amount) {
    // check that actual GroceryItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting amount of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    int actualAmount = actual.getAmount();
    if (actualAmount != amount) {
      failWithMessage(assertjErrorMessage, actual, amount, actualAmount);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual GroceryItem's groceryList is equal to the given one.
   * @param groceryList the given groceryList to compare the actual GroceryItem's groceryList to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GroceryItem's groceryList is not equal to the given one.
   */
  public S hasGroceryList(Grocerylist groceryList) {
    // check that actual GroceryItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting groceryList of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Grocerylist actualGroceryList = actual.getGroceryList();
    if (!Objects.areEqual(actualGroceryList, groceryList)) {
      failWithMessage(assertjErrorMessage, actual, groceryList, actualGroceryList);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual GroceryItem's id is equal to the given one.
   * @param id the given id to compare the actual GroceryItem's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GroceryItem's id is not equal to the given one.
   */
  public S hasId(int id) {
    // check that actual GroceryItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // check
    int actualId = actual.getId();
    if (actualId != id) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual GroceryItem's product is equal to the given one.
   * @param product the given product to compare the actual GroceryItem's product to.
   * @return this assertion object.
   * @throws AssertionError - if the actual GroceryItem's product is not equal to the given one.
   */
  public S hasProduct(Product product) {
    // check that actual GroceryItem we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting product of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Product actualProduct = actual.getProduct();
    if (!Objects.areEqual(actualProduct, product)) {
      failWithMessage(assertjErrorMessage, actual, product, actualProduct);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
