package com.yougrocery.yougrocery.models;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;

/**
 * Abstract base class for {@link ProductOnGrocerylist} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractProductOnGrocerylistAssert<S extends AbstractProductOnGrocerylistAssert<S, A>, A extends ProductOnGrocerylist> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractProductOnGrocerylistAssert}</code> to make assertions on actual ProductOnGrocerylist.
   * @param actual the ProductOnGrocerylist we want to make assertions on.
   */
  protected AbstractProductOnGrocerylistAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

  /**
   * Verifies that the actual ProductOnGrocerylist's groceryList is equal to the given one.
   * @param groceryList the given groceryList to compare the actual ProductOnGrocerylist's groceryList to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProductOnGrocerylist's groceryList is not equal to the given one.
   */
  public S hasGroceryList(Grocerylist groceryList) {
    // check that actual ProductOnGrocerylist we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting groceryList of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Grocerylist actualGroceryList = actual.getGroceryList();
    if (!Objects.areEqual(actualGroceryList, groceryList)) {
      failWithMessage(assertjErrorMessage, actual, groceryList, actualGroceryList);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual ProductOnGrocerylist's id is equal to the given one.
   * @param id the given id to compare the actual ProductOnGrocerylist's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProductOnGrocerylist's id is not equal to the given one.
   */
  public S hasId(java.util.UUID id) {
    // check that actual ProductOnGrocerylist we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    java.util.UUID actualId = actual.getId();
    if (!Objects.areEqual(actualId, id)) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return myself;
  }

  /**
   * Verifies that the actual ProductOnGrocerylist's product is equal to the given one.
   * @param product the given product to compare the actual ProductOnGrocerylist's product to.
   * @return this assertion object.
   * @throws AssertionError - if the actual ProductOnGrocerylist's product is not equal to the given one.
   */
  public S hasProduct(Product product) {
    // check that actual ProductOnGrocerylist we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting product of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Product actualProduct = actual.getProduct();
    if (!Objects.areEqual(actualProduct, product)) {
      failWithMessage(assertjErrorMessage, actual, product, actualProduct);
    }

    // return the current assertion for method chaining
    return myself;
  }

}
