package com.yougrocery.yougrocery.models;

/**
 * {@link Grocerylist} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractGrocerylistAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class GrocerylistAssert extends AbstractGrocerylistAssert<GrocerylistAssert, Grocerylist> {

  /**
   * Creates a new <code>{@link GrocerylistAssert}</code> to make assertions on actual Grocerylist.
   * @param actual the Grocerylist we want to make assertions on.
   */
  public GrocerylistAssert(Grocerylist actual) {
    super(actual, GrocerylistAssert.class);
  }

  /**
   * An entry point for GrocerylistAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGrocerylist)</code> and get specific assertion with code completion.
   * @param actual the Grocerylist we want to make assertions on.
   * @return a new <code>{@link GrocerylistAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static GrocerylistAssert assertThat(Grocerylist actual) {
    return new GrocerylistAssert(actual);
  }
}
