package com.yougrocery.yougrocery.models;

/**
 * {@link GroceryItem} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractGroceryItemAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class GroceryItemAssert extends AbstractGroceryItemAssert<GroceryItemAssert, GroceryItem> {

  /**
   * Creates a new <code>{@link GroceryItemAssert}</code> to make assertions on actual GroceryItem.
   * @param actual the GroceryItem we want to make assertions on.
   */
  public GroceryItemAssert(GroceryItem actual) {
    super(actual, GroceryItemAssert.class);
  }

  /**
   * An entry point for GroceryItemAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myGroceryItem)</code> and get specific assertion with code completion.
   * @param actual the GroceryItem we want to make assertions on.
   * @return a new <code>{@link GroceryItemAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static GroceryItemAssert assertThat(GroceryItem actual) {
    return new GroceryItemAssert(actual);
  }
}
