package com.yougrocery.yougrocery.models;

/**
 * {@link ProductOnGrocerylist} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractProductOnGrocerylistAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ProductOnGrocerylistAssert extends AbstractProductOnGrocerylistAssert<ProductOnGrocerylistAssert, ProductOnGrocerylist> {

  /**
   * Creates a new <code>{@link ProductOnGrocerylistAssert}</code> to make assertions on actual ProductOnGrocerylist.
   * @param actual the ProductOnGrocerylist we want to make assertions on.
   */
  public ProductOnGrocerylistAssert(ProductOnGrocerylist actual) {
    super(actual, ProductOnGrocerylistAssert.class);
  }

  /**
   * An entry point for ProductOnGrocerylistAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myProductOnGrocerylist)</code> and get specific assertion with code completion.
   * @param actual the ProductOnGrocerylist we want to make assertions on.
   * @return a new <code>{@link ProductOnGrocerylistAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ProductOnGrocerylistAssert assertThat(ProductOnGrocerylist actual) {
    return new ProductOnGrocerylistAssert(actual);
  }
}
