package com.yougrocery.yougrocery.models;

/**
 * {@link ProductOnGrocerylist.ProductOnGrocerylistBuilder} specific assertions - Generated by CustomAssertionGenerator.
 *
 * Although this class is not final to allow Soft assertions proxy, if you wish to extend it, 
 * extend {@link AbstractProductOnGrocerylistProductOnGrocerylistBuilderAssert} instead.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ProductOnGrocerylistProductOnGrocerylistBuilderAssert extends AbstractProductOnGrocerylistProductOnGrocerylistBuilderAssert<ProductOnGrocerylistProductOnGrocerylistBuilderAssert, ProductOnGrocerylist.ProductOnGrocerylistBuilder> {

  /**
   * Creates a new <code>{@link ProductOnGrocerylistProductOnGrocerylistBuilderAssert}</code> to make assertions on actual ProductOnGrocerylist.ProductOnGrocerylistBuilder.
   * @param actual the ProductOnGrocerylist.ProductOnGrocerylistBuilder we want to make assertions on.
   */
  public ProductOnGrocerylistProductOnGrocerylistBuilderAssert(ProductOnGrocerylist.ProductOnGrocerylistBuilder actual) {
    super(actual, ProductOnGrocerylistProductOnGrocerylistBuilderAssert.class);
  }

  /**
   * An entry point for ProductOnGrocerylistProductOnGrocerylistBuilderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myProductOnGrocerylist.ProductOnGrocerylistBuilder)</code> and get specific assertion with code completion.
   * @param actual the ProductOnGrocerylist.ProductOnGrocerylistBuilder we want to make assertions on.
   * @return a new <code>{@link ProductOnGrocerylistProductOnGrocerylistBuilderAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ProductOnGrocerylistProductOnGrocerylistBuilderAssert assertThat(ProductOnGrocerylist.ProductOnGrocerylistBuilder actual) {
    return new ProductOnGrocerylistProductOnGrocerylistBuilderAssert(actual);
  }
}
